// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeeLRUniDrpRWt-fu4FE8-cNnwlgSeFRs',
    appId: '1:845825639162:web:587f55843e328b391dbf43',
    messagingSenderId: '845825639162',
    projectId: 'safevan-4251e',
    authDomain: 'safevan-4251e.firebaseapp.com',
    storageBucket: 'safevan-4251e.firebasestorage.app',
    measurementId: 'G-2QRJZ5ZDZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr_mjtxX0ytoGSZLOtvPSdyNEuG0EKzWg',
    appId: '1:845825639162:android:f6a65b51d80697d71dbf43',
    messagingSenderId: '845825639162',
    projectId: 'safevan-4251e',
    storageBucket: 'safevan-4251e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFlUbeUqCH-HIISGFU3h6d64Q4oT6967M',
    appId: '1:845825639162:ios:2fa9ef7570b0a2661dbf43',
    messagingSenderId: '845825639162',
    projectId: 'safevan-4251e',
    storageBucket: 'safevan-4251e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeeLRUniDrpRWt-fu4FE8-cNnwlgSeFRs',
    appId: '1:845825639162:web:97e9ad8ca4686ab21dbf43',
    messagingSenderId: '845825639162',
    projectId: 'safevan-4251e',
    authDomain: 'safevan-4251e.firebaseapp.com',
    storageBucket: 'safevan-4251e.firebasestorage.app',
    measurementId: 'G-Y8VC89THPJ',
  );
}
